In [1]:
import pandas as pd

In [2]:
#data load
data = pd.read_csv("dataset_Facebook.csv", sep=';')

print(data.head())

   Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
0            139441   Photo         2          12             4          3   
1            139441  Status         2          12             3         10   
2            139441   Photo         3          12             3          3   
3            139441   Photo         2          12             2         10   
4            139441   Photo         2          12             2          3   

   Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0   0.0                       2752                             5091   
1   0.0                      10460                            19057   
2   0.0                       2413                             4373   
3   1.0                      50128                            87991   
4   0.0                       7244                            13594   

   Lifetime Engaged Users  Lifetime Post Consumers  \
0                     178                      109

In [3]:
#create data subset
subset = data[["Page total likes", "Type", "like", "comment", "share"]]

print(subset.head())

   Page total likes    Type    like  comment  share
0            139441   Photo    79.0        4   17.0
1            139441  Status   130.0        5   29.0
2            139441   Photo    66.0        0   14.0
3            139441   Photo  1572.0       58  147.0
4            139441   Photo   325.0       19   49.0


In [4]:
#merge data
data1 = data[["Page total likes", "Type"]]

data2 = data[["like", "comment", "share"]]

merged_data = pd.concat([data1, data2], axis=1)

print(merged_data.head())

   Page total likes    Type    like  comment  share
0            139441   Photo    79.0        4   17.0
1            139441  Status   130.0        5   29.0
2            139441   Photo    66.0        0   14.0
3            139441   Photo  1572.0       58  147.0
4            139441   Photo   325.0       19   49.0


In [5]:
#sort data
sorted_data = data.sort_values(by="like", ascending=False)

print(sorted_data[["Type", "like"]].head())

      Type    like
244  Photo  5172.0
379  Photo  1998.0
349  Photo  1639.0
168  Photo  1622.0
3    Photo  1572.0


In [6]:
#transpose data
transpose_data = data.head().T

print(transpose_data)

                                                         0       1       2  \
Page total likes                                    139441  139441  139441   
Type                                                 Photo  Status   Photo   
Category                                                 2       2       3   
Post Month                                              12      12      12   
Post Weekday                                             4       3       3   
Post Hour                                                3      10       3   
Paid                                                   0.0     0.0     0.0   
Lifetime Post Total Reach                             2752   10460    2413   
Lifetime Post Total Impressions                       5091   19057    4373   
Lifetime Engaged Users                                 178    1457     177   
Lifetime Post Consumers                                109    1361     113   
Lifetime Post Consumptions                             159    16

In [7]:
#reshape data
reshaped_data = data[["like", "comment", "share"]].values.reshape(-1, 3)

print(reshaped_data)

[[ 79.   4.  17.]
 [130.   5.  29.]
 [ 66.   0.  14.]
 ...
 [ 93.   4.  18.]
 [ 91.   7.  38.]
 [ 91.   0.  28.]]
